# Generated by Django 3.2.7 on 2021-09-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filenanme', models.FileField(upload_to='downloads')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
