# Generated by Django 3.2.7 on 2021-09-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfiles',
            old_name='filenanme',
            new_name='file',
        ),
    ]
